import { Header } from '@/components/Layout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren, ReactNode } from 'react'
import Footer from '@/components/Layout/Footer'
import { Head } from 'next/dist/pages/_document'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type MainProps = PropsWithChildren<{
  meta: ReactNode;
}>

export default function RootLayout({
  children,
  meta
}: MainProps) {
  return (
    <html lang="en">
      <Header />
      <body className={inter.className}>{children}</body>
      <Footer />
    </html>
  )
}
